In [1]:
import morePVs_output as opm
import morePVs as mpv
import os
import en_utilities as um
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.lines as mlines

Plotting Total Building Costs
-----------------------------------


Plotting Total costs as % of `en` (ie no pv)

In [2]:
#
# Need to set this up using combined_value4 as the study
project='EN1_value_of_pv'
study_name='combined_value4'
base_path='C:\\Users\\z5044992\\Documents\\MainDATA\\DATA_EN_3\\studies'
op = opm.Output(base_path = base_path,
                          project = project,
                          study_name = study_name)

In [3]:
op.plot_path = 'C:\\Users\\z5044992\\Documents\\MainDATA\\DATA_EN_3\\studies\\EN1_value_of_pv\\outputs\\combined_value4\\plots3'

In [4]:
self = op
df = self.data.copy()
df_in = self.study_parameters.copy()

df=df.set_index(['ns'])
df.head()

,scenario_label,arrangement,number_of_households,load_folder,en_opex,en_capex_repayment,pv_capex_repayment,average_hh_bill$,average_hh_total$,NUOS_charges$_mean,...,eno$_receipts_from_residents_mean,eno$_total_payment_mean,eno_net$_mean,export_kWh_mean,import_kWh_mean,pv_ratio_mean,retailer_receipt$_mean,self-consumption_mean,total$_building_costs_mean,total_building_load_mean
ns,,,,,,,,,,,,,,,,,,,,,
A0,siteA_value4_000,bau,208.0,h_all_site_A,0.0,0.0,0.000000,1210.652254,1210.652254,46188.856790,...,0.0,0.0,0.0,0.000000,1.079092e+06,0.000000,344031.979307,0.000000,344031.979307,1.079092e+06
A1,siteA_value4_001,cp_only,208.0,h_all_site_A,0.0,0.0,18854.121364,1210.652254,1210.652254,44630.401471,...,0.0,0.0,0.0,4.685924,1.015101e+06,5.935119,326734.025897,99.992678,345588.147260,1.079092e+06
A2,siteA_value4_002,cp_only,208.0,h_all_site_A,0.0,0.0,8938.704693,1210.652254,1210.652254,44630.401471,...,0.0,0.0,0.0,4.685924,1.015101e+06,5.935119,326734.025897,99.992678,335672.730590,1.079092e+06
A3,siteA_value4_003,cp_only,208.0,h_all_site_A,0.0,0.0,5358.828401,1210.652254,1210.652254,44630.401471,...,0.0,0.0,0.0,4.685924,1.015101e+06,5.935119,326734.025897,99.992678,332092.854298,1.079092e+06
A4,siteA_value4_004,cp_only,208.0,h_all_site_A,0.0,0.0,4549.623794,1210.652254,1210.652254,44630.401471,...,0.0,0.0,0.0,4.685924,1.015101e+06,5.935119,326734.025897,99.992678,331283.649691,1.079092e+06

In [5]:
df_in.head()

,pv_filename,load_folder,arrangement,pv_cap_id,cp,all_residents,parent,network_tariff,en_capex_id,a_term,a_rate
scenario,,,,,,,,,,,
A0,NaN,h_all_site_A,bau,NaN,EASO_TOU_15pc_FIT8,EASO_TOU_15pc_FIT8,TIDNULL,EA310,NaN,5.0,0.06
A1,vb_pv\site_A_max.csv,h_all_site_A,cp_only,site_A_max,EASO_TOU_15pc_FIT8,EASO_TOU_15pc_FIT8,TIDNULL,EA310,NaN,5.0,0.06
A2,vb_pv\site_A_max.csv,h_all_site_A,cp_only,site_A_max,EASO_TOU_15pc_FIT8,EASO_TOU_15pc_FIT8,TIDNULL,EA310,NaN,10.0,0.06
A3,vb_pv\site_A_max.csv,h_all_site_A,cp_only,site_A_max,EASO_TOU_15pc_FIT8,EASO_TOU_15pc_FIT8,TIDNULL,EA310,NaN,15.0,0.06
A4,vb_pv\site_A_max.csv,h_all_site_A,cp_only,site_A_max,EASO_TOU_15pc_FIT8,EASO_TOU_15pc_FIT8,TIDNULL,EA310,NaN,20.0,0.06

In [6]:

df = df.merge(df_in,left_index = True, right_index=True)
for c in df.columns:
    if '_x' in c:
        nc = c[:-2]
        df.rename(columns={c:nc}, inplace=True)
df.head()

,scenario_label,arrangement,number_of_households,load_folder,en_opex,en_capex_repayment,pv_capex_repayment,average_hh_bill$,average_hh_total$,NUOS_charges$_mean,...,load_folder_y,arrangement_y,pv_cap_id,cp,all_residents,parent,network_tariff,en_capex_id,a_term,a_rate
A0,siteA_value4_000,bau,208.0,h_all_site_A,0.0,0.0,0.000000,1210.652254,1210.652254,46188.856790,...,h_all_site_A,bau,NaN,EASO_TOU_15pc_FIT8,EASO_TOU_15pc_FIT8,TIDNULL,EA310,NaN,5.0,0.06
A1,siteA_value4_001,cp_only,208.0,h_all_site_A,0.0,0.0,18854.121364,1210.652254,1210.652254,44630.401471,...,h_all_site_A,cp_only,site_A_max,EASO_TOU_15pc_FIT8,EASO_TOU_15pc_FIT8,TIDNULL,EA310,NaN,5.0,0.06
A2,siteA_value4_002,cp_only,208.0,h_all_site_A,0.0,0.0,8938.704693,1210.652254,1210.652254,44630.401471,...,h_all_site_A,cp_only,site_A_max,EASO_TOU_15pc_FIT8,EASO_TOU_15pc_FIT8,TIDNULL,EA310,NaN,10.0,0.06
A3,siteA_value4_003,cp_only,208.0,h_all_site_A,0.0,0.0,5358.828401,1210.652254,1210.652254,44630.401471,...,h_all_site_A,cp_only,site_A_max,EASO_TOU_15pc_FIT8,EASO_TOU_15pc_FIT8,TIDNULL,EA310,NaN,15.0,0.06
A4,siteA_value4_004,cp_only,208.0,h_all_site_A,0.0,0.0,4549.623794,1210.652254,1210.652254,44630.401471,...,h_all_site_A,cp_only,site_A_max,EASO_TOU_15pc_FIT8,EASO_TOU_15pc_FIT8,TIDNULL,EA310,NaN,20.0,0.06

In [7]:
#df = df[df['arrangement'].isin(['bau', 'en', 'en_pv', 'btm_icp'])]
df = df[df['arrangement'].isin([ 'en', 'en_pv', 'btm_icp'])]

In [8]:
# Set up constants
sites=['A','E','D','B','H','I','G','C','J','F']
# Plotting set-up parameters
cmap = mpl.cm.tab10
alpha=1

markers =['x','o','D','*','^','H','s','v','>','<']
site_markers = dict(zip(sites,markers))

colours = ['tab:blue', 'tab:orange', 'tab:green', 'tab:red', 'tab:purple', 'tab:brown', 'tab:pink', 'tab:gray', 'tab:olive', 'tab:cyan']
site_colours = dict(zip(sites,colours))

a_terms =[a for a in [5,10,15,20,25] if a in df.a_term.tolist()]
dashList = [(2,8),(3,5),(10,0),(3,2,10,2),(5,2,20,2)] 
markers =['+','o','d','s','x']
term_dashes = dict(zip(a_terms,dashList))
term_markers = dict(zip(a_terms,markers))


# get pv sizes for maximum pv systems
maximums={}
pv_ref_file='C:\\Users\\z5044992\\Documents\\MainDATA\\DATA_EN_3\\reference\\capex_pv_lookup.csv'
pv_ref=pd.read_csv(pv_ref_file)
pv_ref = pv_ref.set_index('pv_cap_id')
for i in pv_ref.index:
    if 'max' in i and 'site' in i:
        site = um.find_between(i,'_','_')
        maximums[site] = pv_ref.loc[i,'kW']
en_capexes= [c for c in ['capex_4','capex_5','capex_6']if c in df.en_capex_id.tolist()]
parents = [p for p in ['EA310_12c_FIT8', 'EA310_12c_FIT12', 'EA310_12c',\
           'EA310_10c_FIT8', 'EA310_10c_FIT12', 'EA310_10c',\
         'EA310_8c_FIT8', 'EA310_8c_FIT12','EA310_8c'] if p in df.parent.tolist()]

In [9]:
# Organise labels 
df.loc[:,'site'] = df.loc[:,'load_folder'].apply(lambda x : x[-1])
df.loc[:, 'labels'] = df.loc[:,'site']
floors = {'A':12,'E':7, 'D':9,'B':8,'H':3,'I':4,'G':4,'C':4,'J':4,'F':5}
numhouses={'A':208,'E':161, 'D':138,'B':104,'H':52,'I':48,'G':44,'C':34,'J':26,'F':20}
labels ={}
for s, f in floors.items():
    u = numhouses[s]
    labels[s] = s +'('+str(u)+'/'+str(f)+')'
print(labels)
df.loc[:, 'label'] = df.loc[:, 'site'].apply(lambda x: labels[x])

{'A': 'A(208/12)', 'E': 'E(161/7)', 'D': 'D(138/9)', 'B': 'B(104/8)', 'H': 'H(52/3)', 'I': 'I(48/4)', 'G': 'G(44/4)', 'C': 'C(34/4)', 'J': 'J(26/4)', 'F': 'F(20/5)'}

In [10]:
# get kWp / unit , total $ / unit  and % bau for each scenario
df['pv_filename'].fillna('zero',inplace=True)
for s in df.index:
    site = df.loc[s,'load_folder'][-1]
    df.loc[s,'site']=site
    if df.loc[s,'pv_filename'] == 'zero':
        df.loc[s,'kwp_unit'] =0
    elif 'max' in df.loc[s,'pv_filename']:
        df.loc[s,'kwp_unit']= maximums[site]/df.loc[s,'number_of_households']
    else:
        df.loc[s,'kwp_unit'] = float(df.loc[s,'pv_filename'][-9]) + float(df.loc[s,'pv_filename'][-7])/10
    df.loc[s,'$_unit'] = df.loc[s,'total$_building_costs_mean']/df.loc[s,'number_of_households']
    #bau_scenario = df[(df['site']==site) & (df['arrangement'] == 'bau')].index
    en_scenario = df[(df['site']==site) & (df['arrangement'] == 'en') & 
                     (df['parent'] == df.loc[s,'parent']) &  (df['a_term'] == df.loc[s,'a_term']) &
                     (df['en_capex_id'] == df.loc[s,'en_capex_id'])].index
                    
    df.loc[s,'en'] = (df.loc[en_scenario,'total$_building_costs_mean']).values[0]/df.loc[s,'number_of_households']
    #df.loc[s,'bau'] = (df.loc[bau_scenario,'total$_building_costs_mean']).values[0]/df.loc[s,'number_of_households']
    df.loc[s,'%_en'] = df.loc[s,'$_unit']/ df.loc[s,'en']*100

In [11]:
max_enpc = df['%_en'].max()
min_enpc = df['%_en'].min()
max_enpc, min_enpc

(182.66199587883082, 78.87850345855952)

In [12]:
op.plot_path = 'C:\\Users\\z5044992\\Documents\\MainDATA\\DATA_EN_3\\studies\\EN1_value_of_pv\\outputs\\combined_value4\\plots_percentage_en'
if not os.path.exists(op.plot_path):
    os.makedirs(op.plot_path)

In [13]:
#LINE PLOTS
for parent, capex in [(parent, capex) for parent in parents for capex in en_capexes]:  
    title = parent + " / " + capex                        
    p_slice = df['parent'] == parent 
    c_slice = df['en_capex_id'] == capex
    dfx=df.copy()[p_slice & c_slice]
    
    # Get rid of duplicates - assumed irrelevant as only variation is internal tariffs
    dfx.loc[:,'kwp_str'] = dfx.loc[:,'kwp_unit'].apply(lambda x : str(round(x,2)))
    dfx.loc[:,'aterm_str'] = dfx.loc[:,'a_term'].apply(lambda x : str(round(x,0)))
    dfx['combined'] = dfx['site']+ '_' + dfx['arrangement'] + '_'+ dfx['kwp_str']+ '_'+(dfx['aterm_str'])
    dfx['arr_pv'] = dfx['arrangement'] + '_'+ dfx['kwp_str']
    dfx = dfx.drop_duplicates('combined')
    #fx['combined'] = dfx['combined'].apply(lambda x: x[1:])
    dfx['new_label']= dfx['label']+ '_'+ dfx['aterm_str']
    
    # ----------------------
    # reindex and stack data
    # ----------------------
    dfx.index = [dfx.new_label,dfx.arr_pv]
    dfu = dfx['%_en'].unstack()

    cols =dfu.columns
    cols = [c[3:] for c in cols ]
    cols = [0.0]+[float(c[3:]) for c in cols if 'pv' in c]
    dfu.columns=cols
    dfv=dfu.transpose()
    dfv


    fig, ax = plt.subplots()
    for a_term in a_terms:
        a_label = '_'+str(a_term)
        for label in [c for c in dfv.columns if a_label in c]:     
            y = dfv[label].dropna()
            x = y.index

            line = ax.plot(x,y,   \
                           alpha=alpha,  c = site_colours[label[0]],\
                           linewidth = 0.5, marker = term_markers[a_term], markersize=2 ,
                           linestyle='--', dashes=term_dashes[a_term])             
                               
    ax.set_title(title, fontsize=16, y=1.0)
    ax.set_xlabel("PV system (kWp)", fontsize=14)
    ax.set_ylabel("Site Costs as % of EN with no PV", fontsize=14)
    ax.grid(True)
    ax.set_ylim((min_enpc*0.9, max_enpc*1.1))

   
    #Legends outside box and resize chart to fit
    box = ax.get_position()
    ax.set_position([box.x0, box.y0, box.width * 0.8, box.height])
    
    # Create Legend for line types
    a_terms=[5,10,15,20,25]
    dashList = [(2,8),(3,5),(10,0),(3,2,10,2),(5,2,20,2)] 
    markers =['+','o','d','s','x']
    term_dashes = dict(zip(a_terms,dashList))
    term_markers = dict(zip(a_terms,markers))
    lline = {}
    for a in a_terms:
        lline[a] = mlines.Line2D([],[],color='black', marker=term_markers[a],
                              linestyle='--', dashes=term_dashes[a],
                                 markersize=3, label=str(a) + " years" )
    handles = [lline[a] for a in a_terms]
    line_legend = ax.legend(handles = handles, loc='upper left', bbox_to_anchor=(1, 0.3),prop={'size': 9})
    # Add the legend manually to the current Axes.
    ax1 = plt.gca().add_artist(line_legend)

    # Create legend for colours
    cline = {}
    for s in sites:
        cline[s] = mlines.Line2D([],[],color=site_colours[s] , label=labels[s])
    handles2 = [cline[s] for s in sites]
    ax.legend(handles = handles2, loc='upper left', bbox_to_anchor=(1, 1),prop={'size': 9})
      
    pname = study_name +'_'+str(a_term) + '_'+ parent+'_' + capex + '.png'
    plotFile = os.path.join(self.plot_path,pname)
    plt.savefig(plotFile,dpi=1000)
    plt.close()

In [ ]:
dfx.head()

In [ ]:
dfv.head()