## testing battery etc
31/3/18
__ First, try out shorter timeseries:__

In [6]:
import pandas as pd
import os
import numpy as np
import datetime as dt

In [13]:
load = pd.read_csv('C:\\Users\\z5044992\\Documents\\MainDATA\DATA_EN_3\\load_profiles\\2day_loads\\profile_2days.csv',
                  parse_dates=['timestamp'],
                                dayfirst=True)
load.set_index('timestamp', inplace=True)

In [14]:
load

                        cp      1      2
timestamp
2013-01-01 00:00:00  19.30  0.106  0.102
2013-01-01 00:30:00  19.35  0.045  0.153
2013-01-01 01:00:00  19.35  0.041  0.139
2013-01-01 01:30:00  19.40  0.034  0.105
2013-01-01 02:00:00  19.20  0.024  0.142
2013-01-01 02:30:00  19.00  0.018  0.146
2013-01-01 03:00:00  19.05  0.019  0.106
2013-01-01 03:30:00  18.85  0.018  0.106
2013-01-01 04:00:00  18.70  0.020  0.155
2013-01-01 04:30:00  18.55  0.021  0.133
2013-01-01 05:00:00  18.55  0.084  0.108
2013-01-01 05:30:00  17.95  0.034  0.106
2013-01-01 06:00:00  17.90  0.414  0.170
2013-01-01 06:30:00  18.20  0.398  0.179
2013-01-01 07:00:00  18.55  0.061  0.185
2013-01-01 07:30:00  18.80  0.019  0.107
2013-01-01 08:00:00  18.80  0.244  0.205
2013-01-01 08:30:00  18.85  0.228  0.137
2013-01-01 09:00:00  18.80  1.318  0.180
2013-01-01 09:30:00  19.15  0.034  0.176
2013-01-01 10:00:00  19.10  0.024  0.147
2013-01-01 10:30:00  19.50  0.023  0.173
2013-01-01 11:00:00  19.40  0.027  0.189
2013-01-01 11:30:00  19.70  0.016  0.148
2013-01-01 12:00:00  19.80  0.018  0.146
2013-01-01 12:30:00  19.50  0.020  0.194
2013-01-01 13:00:00  19.70  0.024  0.141
2013-01-01 13:30:00  19.30  0.024  0.177
2013-01-01 14:00:00  19.75  0.027  0.186
2013-01-01 14:30:00  19.50  0.024  0.152
...                    ...    ...    ...
2013-01-02 09:00:00  19.45  0.957  0.178
2013-01-02 09:30:00  20.25  0.022  0.171
2013-01-02 10:00:00  20.05  0.020  0.103
2013-01-02 10:30:00  19.85  0.018  0.132
2013-01-02 11:00:00  20.00  0.019  0.153
2013-01-02 11:30:00  19.70  0.015  0.107
2013-01-02 12:00:00  20.15  0.021  0.123
2013-01-02 12:30:00  19.75  0.022  0.164
2013-01-02 13:00:00  19.65  0.023  0.106
2013-01-02 13:30:00  19.45  0.022  0.106
2013-01-02 14:00:00  19.50  0.021  0.169
2013-01-02 14:30:00  19.65  0.027  0.125
2013-01-02 15:00:00  19.50  0.022  0.225
2013-01-02 15:30:00  19.55  0.016  0.141
2013-01-02 16:00:00  19.95  0.019  0.200
2013-01-02 16:30:00  19.95  0.016  0.241
2013-01-02 17:00:00  19.95  0.022  0.233
2013-01-02 17:30:00  19.35  0.020  0.137
2013-01-02 18:00:00  19.80  0.023  0.211
2013-01-02 18:30:00  19.60  0.681  0.130
2013-01-02 19:00:00  20.25  0.034  0.152
2013-01-02 19:30:00  19.80  0.026  0.189
2013-01-02 20:00:00  19.80  0.018  0.232
2013-01-02 20:30:00  19.70  0.020  0.296
2013-01-02 21:00:00  19.85  0.018  0.187
2013-01-02 21:30:00  19.40  0.016  0.165
2013-01-02 22:00:00  19.45  0.019  0.247
2013-01-02 22:30:00  19.40  0.019  0.228
2013-01-02 23:00:00  19.35  0.021  0.099
2013-01-02 23:30:00  18.90  0.021  0.187

[96 rows x 3 columns]

In [15]:
timeseries = load.index
num_steps = len(timeseries)
interval = \
                pd.to_timedelta(
                pd.tseries.frequencies.to_offset(
                pd.infer_freq(timeseries)
                )).total_seconds()

In [17]:
interval

1800.0

In [20]:
num_days = int(num_steps * interval / (24*60*60))
        # Set up weekdays and weekends
days = {
            'day': timeseries[timeseries.weekday.isin([0, 1, 2, 3, 4])],
            'end': timeseries[timeseries.weekday.isin([5, 6])],
            'both': timeseries}

In [22]:
num_days

2

In [ ]:
load.head()